export const BASE_URL = '/monuments'
export const APP_URL = process.env.NODE_ENV === 'production' ? 'https://www.yatra.com/monuments' : 'http://yatra.com/monuments'
export const DOMAIN_URL = process.env.NODE_ENV === 'production' ? 'https://www.yatra.com' :'http://yatra.com'
export const API_URL = '/get-asi-data/asiAPI'
export const ACT_API_URL = '/get-activity-data'
export const HOTEL_API_URL = '/get-hotel-data'
export const HOTEL_API_KEY = 'JN9aWyj7hJ1ZrExC7Ozo'
export const SSO_LOGIN_URL = 'https://secure.yatra.com/social/common/yatra/signin.htm'
export const USER_Profile_URL = '/social/user/userProfile.htm'
export const COM_TENANT_ID = 5406
//export const API_CART_URL = 'get-cart'
//export const API_CART_URL = process.env.NODE_ENV === 'production' ? 'https://secure.yatra.com/cartservice/services' : 'get-cart'
export const API_CART_URL = process.env.NODE_ENV === 'production' ? '/cartservice/services' : 'get-cart'
export const API_WHTSAPP_URL = process.env.NODE_ENV === 'production' ? '/userprofileservice/' : '/userprofileservice/'